### PR TITLE
Reinstate custom container support

### PR DESCRIPTION
**Pull request by rachetfoot**
This was removed recently in an unrelated commit (bad merge resolution?) This commit gets it back.

### CODE REVIEW

**Comment by Slyke** [comment]
It was removed on purpose. There's now a `compose-override.yml` file that you can place in the directory, that will be merged into the main `docker-compose.yml` file during build (of the stack) time.

I've put details on how to use it in this PR: https://github.com/SensorsIot/IOTstack/pull/38

**Comment by rachetfoot** [comment]
Oh really? Can I suggest changing the documentation so the user by default installs a version of IOTstack that matches the documentation? E.g. stable branch (or move development to a different branch) This discrepancy was an unnecessary source of frustration for me.

**Comment by Slyke** [comment]
Yep. Sorry about that. I totally understand. We are currently in the works of updating the documentation.

**Comment by Slyke** [comment]
I have just updated the documentation and submitted the changes in PR https://github.com/SensorsIot/IOTstack/pull/79/files

**Comment by Slyke** [comment]
I have updated the documentation. Please have a read: https://sensorsiot.github.io/IOTstack/Custom/ If you're happy with it, I'll close this PR.

**Comment by rachetfoot** [comment]
Thanks. Beyond the title, custom containers aren't mentioned at all. I'd suggest adding a sentence or two saying that it can also be used to add customer containers and that it's done by adding a new section to the overrides file (the name of which is a bit of a misnomer IMHO, since in that case we are not actually 'overriding' anything).

**Comment by Slyke** [comment]
I've updated the documentation. You can view the latest (as of yet) unmerged version here: https://github.com/SensorsIot/IOTstack/blob/3822c8c23af37699f0c90ff49dab8723d73ab878/docs/Custom.md

I added a full example, copying the outputs as is into the documentation.

**Comment by rachetfoot** [comment]
Great, looks good to me.

**Pull request closed without merging**
