### PR TITLE
20220602 InfluxDB 2 - master branch - PR 1 of 3

### LINKED ISSUE #132: Portainer/Portatiner is now deprecated
Portainer/Portatiner is now deprecated. Can you update it so it is using **portainer/portainer-ce**.  [https://hub.docker.com/r/portainer/portainer-ce](url)

### LINKED ISSUE #169: Portainer menu.sh
Hi, if i select portainer-ce and build the stack, on the next run of menu.sh portainer and portainer-ce are selected.
On every run i must deselect portainer. selection.txt only contains portainer-ce

### LINKED ISSUE #279: InfluxDB install gives error: "ERROR: no matching manifest for linux/arm/v7 in the manifest list entries"
I installed Grafana, influxdb, node-red and portainer-ce without issue just last week.

I tried to do a new install today and influxdb seems to break everything.

I see the following error:
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

When I checked the Influx docker page, it seems they may have changed settings to use the 2.0 version of Influxdb.

I edited the docker-compose.yml line for influxdb, changing: 

image: "influxdb:latest"

to

image: "influxdb:1.8"

Which resolved the issue.

Apologies if I have not provided all of the correct information -- Docker and IOTStack are both new to me as of last week.

### LINKED ISSUE #289: Remove portainer in favor of portainer-ce
If I'm correct the preferred container for portainer is now portainer-ce (community edition).

Can somebody remove portainer from the list to avoid confusion?

### LINKED ISSUE #455: updated Influxdb container
Hello,

I've updated all containers and influxdb is now version 2.1.1.
Although it may be not working for some people, I'm using bullseye 64bit on a RPI4 and the database goes up properly (it gets in "green running" in portainer CE) and I'm able to access its web GUI.

However, its way of working seems to be different from the previous release (18.x). The commands from the earlier version don't seem to work. For instance, the "influx" command isn't interactive anymore.

```
pi@raspberrypi:~/IOTstack/services/influxdb $ ./terminal.sh
You are about to enter the influxdb console:

to create a db: CREATE DATABASE myname
to show existing a databases: SHOW DATABASES
to use a specific db: USE myname

to exit type: EXIT

NAME:
   influx - Influx Client

USAGE:
   influx [command]

COMMANDS:
   version              Print the influx CLI version
   ping                 Check the InfluxDB /health endpoint
   setup                Setup instance with initial user, org, bucket
   write                Write points to InfluxDB
   bucket               Bucket management commands
   completion           Generates completion scripts
   bucket-schema        Bucket schema management commands
   query                Execute a Flux query
   config               Config management commands
   org, organization    Organization management commands
   delete               Delete points from InfluxDB
   user                 User management commands
   task                 Task management commands
   backup               Backup database
   restore              Restores a backup directory to InfluxDB
   telegrafs            List Telegraf configuration(s). Subcommands manage Telegraf configurations.
   dashboards           List Dashboard(s).
   export               Export existing resources as a template
   secret               Secret management commands
   v1                   InfluxDB v1 management commands
   auth, authorization  Authorization management commands
   apply                Apply a template to manage resources
   stacks               List stack(s) and associated templates. Subcommands manage stacks.
   template             Summarize the provided template
   help, h              Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h  show help
pi@raspberrypi:~/IOTstack/services/influxdb $ file terminal.sh
terminal.sh: Bourne-Again shell script, ASCII text executable
pi@raspberrypi:~/IOTstack/services/influxdb $ cat terminal.sh
#!/bin/bash

echo "You are about to enter the influxdb console:"
echo ""
echo "to create a db: CREATE DATABASE myname"
echo "to show existing a databases: SHOW DATABASES"
echo "to use a specific db: USE myname"
echo ""
echo "to exit type: EXIT"
echo ""

docker exec -it influxdb influx
pi@raspberrypi:~/IOTstack/services/influxdb $
```

Are there any plans to update the documentation in order to show how to configure it?   Or would it be recommended to remain in 1.8.x? In that case, any plan to update menu so it fetches version 1.8 only?

Thanks,

### PR DESCRIPTION
**Pull request by Paraphraser**
Adds InfluxDB 2 container and documentation.

Fixes #455, Fixes #289, Fixes #279, Fixes #169, Fixes #132

Signed-off-by: Phill Kelley <34226495+Paraphraser@users.noreply.github.com>

### CODE REVIEW

**Comment by ukkopahis** [comment]
image

This will cause confusion & support issues from users trying to use it on a 32bit OS. Beginners can't be assumed to know better. And beginners are the target group for this project.

Should either:
* only be visible when run on a 64bit OS, or at least
* show a disclaimer in the menu: `(  ) influxdb2 (requires a 64bit OS!)` 

I know it states the 64-bit requirement in the doc-page, but the menu shouldn't ever generate an invalid docker-compose.yml.

**Comment by ukkopahis** [comment]
image

This will cause confusion & support issues from users trying to use it on a 32bit OS. Beginners can't be assumed to know better. And beginners are the target group for this project.

Should either:
* only be visible when run on a 64bit OS, or at least
* show a disclaimer in the menu: `(  ) influxdb2 (requires a 64bit OS!)` 

I know it states the 64-bit requirement in the doc-page, but the menu shouldn't ever generate an invalid docker-compose.yml.

**Review by Slyke — APPROVED** [review]

**Comment by Slyke** [comment]
I still use 1.8 personally, because you need to ssh to run any commands on 2, such as adding users etc.

**Comment by Paraphraser** [comment]
Sorry for the late comment.

I haven't found any need to run ssh. I can still open a shell into the Influx2 container with `docker exec` and do whatever needs to be done.

But I agree. Even though I've figured out the **how** of migration and have documented it here, I'm far from ready to migrate my own data from 1.8. For me the biggest issue is Grafana's inability to create Flux-based queries like it can for InfluxQL. Sure, there's a workaround. You can use Influx2's web GUI to generate the query which you can then copy and paste into Grafana. That does work but it's tedious. I have no plans to revisit this question until Grafana catches up.

Also, I did take a shortcut with Influx2 in the sense that I had one set of credentials to rule them all. I took a brief look at the, err, "excess of functionality" for Influx2 security and my eyes glazed over.

**Pull request merged**
