### PR TITLE
Documentation fixes and improvements

### LINKED ISSUE #497: broken link
Portainer link on https://sensorsiot.github.io/IOTstack/Home/ is broken

### LINKED ISSUE #500: pi-hole not setting default password.
After installing Pi-hole.  The default password listed on https://sensorsiot.github.io/IOTstack/Containers/Pi-hole/ doesn't seem to work.  

I was able to log in with by resetting it with 
`docker exec -it pihole sudo pihole -a -p`

### PR DESCRIPTION
**Pull request by ukkopahis**
One pull request to gather improvements and fixes to the documentation.

Fixes: 
* Dead links corrected
* Markdown formatting errors. The added newlines are **required** for mkdocs to correctly process formatting.
* Container menu-listing to be alphabetically ordered.

Improvements: 
* Pi-hole DNS routing setup and troubleshooting
* How to update containers with git & docker
* Influxdb database creation, retention policy changes, sd-card wear-out prevention
* Home-assistant https reverse proxy and certificate setup using swag to enable google assistant integration 
* How to write docs: mkdocs references and testing locally
* Wireguard PEERDNS=auto works together with changes to host's resolveconf.conf
* Add Discord link to Wiki home page

Changes: 
* Add top tabs: IOTstack Wiki, Basic setup, Containers, Developers
  (these were chosen in order to be in a sensible alphabetical order)
* Update-related pages organized into the "Basic setup/Updates" subtopic, to make the left menu a bit clearer.
* Files moved to corresponding folders and links updated and redirects from old locations added as not to break existing links on the web.
* Remove custom anchor links and generate them automatically using the "toc" markdown extension. This fixes the blue coloring of the headings, which especially impacts users selecting the dark theme.

Resolves:
* Relevant changes from PR #338 are included, and it can be closed when this is merged.
* Fixes #497
* Fixes #500

New top tabs look like this ([live version](https://ukkopahis.github.io/IOTstack/)):
Screenshot_2022-01-26_02-10-47-doc-improvement

And in dark mode:
Screenshot_2022-01-26_02-08-23-doc-improvement

### CODE REVIEW

**Comment by ukkopahis** [comment]
As a convenience, this and most other recent pull-request are available merged in my repository:
https://github.com/ukkopahis/IOTstack/tree/master/

These changes are also updated to the documentation page available at:
https://ukkopahis.github.io/IOTstack/

**Comment by ukkopahis** [comment]
Some users could benefit from merging this.
Screenshot_2022-01-25_23-59-55 influxdb-docs-update-needed

**Review by Slyke — APPROVED** [review]

**Comment by Slyke** [comment]
Hey @ukkopahis sorry this took so long to review. I've approved it now, but it looks like there are now some merge conflicts. I wasn't able to resolve them myself as I can't push to your remote.

**Comment by ukkopahis** [comment]
Pull-requests like #489 and #501 changed the same files as this, and as such only one of them could be cleanly merged.

I'll do a rebase and hope for better luck next time. Don't know why you couldn't push to my branch. I have "allow edits" ticked:
466-allow-edits

**Comment by ukkopahis** [comment]
Github lost your already reviewed changed when I tried rebasing. So here's the conflict-resolution as a merge commit, and a couple new commits.

Ps. you can close #338 when this is merged.

**Comment by ukkopahis** [comment]
Stack icon changed from default to:
iotstack-stack-icon

**Review by Paraphraser — COMMENTED** [review]
I realise this is a bit late but, on reflection, I think that moving the "a word about sudo" material to another file might not be a particularly good idea. Rolling back the clock a bit to something like 18 months ago, it seemed like 2 out of every 3 problems raised on Discord could be traced back to improper use of sudo. That fell right off once those words went into the getting started doco. Granted, I also added code to many scripts saying "don't run this with sudo" and that probably also had an impact. But the "getting started" document is The Key Document referred to in the primary read-me. That really puts the words about sudo "in ya face" for new users. I'm not sure it will have the same mindshare if it is moved. I'm sure I don't need to tell you the kinds of chaos that can be created from improper use of sudo. People with reasonable Linux experience probably wouldn't make the mistake in the first place but, if they did, would probably be able to recognise the problem and undo the damage. Those aren't the people I worry about. I worry about people who just follow gists and web pages, who see a Pi as a means to an end rather than something they want to develop a deep understanding of, and who get horribly stuck if they make a basic mistake like `sudo git clone ... IOTstack` and then find nothing works. I'm not saying "put it back". I'm just asking you to keep these comments in mind if there's an uptick in sudo-related problems in issues and on Discord.

**Comment by ukkopahis** [comment]
> But the "getting started" document is The Key Document referred to in the primary read-me

I don't think very long "Getting Started" is user friendly. 

> it seemed like 2 out of every 3 problems raised on Discord could be traced back to improper use of sudo

Good info. I'll monitor for such problems re-occurring, and correct back if needed.

I'm still planning to:
* extract most from "stack maintenance" to https://sensorsiot.github.io/IOTstack/Updates/ - leave an executive summary
* [New installation/scripted](https://sensorsiot.github.io/IOTstack/Basic_setup/#scripted) links to how to update docker, not how to script IOTstack install. Remove or fix this, do you have a suggestion @Paraphraser ?
* [logging journald errors](https://sensorsiot.github.io/IOTstack/Basic_setup/#logging-journald-errors) talks about /etc/docker/daemon.json, which doesn't even exist on my pi. Have to look into log2ram to fix this properly. Maybe move this into a FAQ/common problems page?
* fix all example commands from `docker` to `docker-compose` (when possible)

**Pull request merged**
