### PR TITLE
Portainer agent

### PR DESCRIPTION
**Pull request by Willem-Dekker**
Allows you to add your docker instance to a portainer instance on a different machine

### CODE REVIEW

**Comment by Slyke** [comment]
When I try this out in incogneto mode I get a white page with the error: `Client sent an HTTP request to an HTTPS server.`

image

When trying this out without incogneto, I get a blank page:
image

Otherwise, the container seems to start up just fine.
image

Is this what it normally does? I have not yet tried adding this to a current Portainer.

Also there is a merge conflict.

**Comment by Willem-Dekker** [comment]
that is not normal there is not a ui that you can access its

**Comment by Slyke** [comment]
Confirmed this is working correctly
image
Once the merge conflict is fixed, I can merge  it.

**Comment by Willem-Dekker** [comment]
@Slyke updated it to master you can merge when ready

**Pull request merged**
