### PR TITLE
Rewritten Menu System

### PR DESCRIPTION
**Pull request by Slyke**
I've spent the last few weeks completely redoing the menu system. Here's my current progress.

Ready to merge to `experimental`. All aspects of this need **thorough** testing in multiple environments to ensure compatibility.

Tested Services:
* &#9745; adminer
* &#9745; blynk_server - Redirects to blynk.cc
* &#9744; deconz
* &#9745; diyhue
* &#9745; dozzle
* &#9745; espruinohub
* &#9745; gitea
* &#9745; grafana
* &#9745; homebridge
* &#9745; influxdb
* &#9745; mariadb
* &#9745; mosquitto
* &#9744; motioneye
* :x: nextcloud
* &#9745; nodered
* &#9745; openhab
* &#9745; pihole
* &#9744; plex
* &#9745; portainer
* &#9745; postgres
* &#9744; python
* &#9744; rtl_433
* &#9745; tasmoadmin
* &#9745; telegraf
* &#9744; timescaledb
* &#9745; transmission
* &#9745; webthings_gateway
* &#9744; zigbee2mqtt
* &#9744; zigbee2mqtt_assistant

Issues:
* nextcloud - Nextcloud's build script needs to support multi service installer (`nextcloud_db`)

MVP TODOs:
* ~~Backup/restore commands~~ - Done
* ~~Ensure NodeRed modules list is up to date.~~ - Done
* ~~Add in group logic specified in https://github.com/SensorsIot/IOTstack/pull/70~~ - Done
* ~~Ensure all containers in master have `build.py` files~~ - Done
* ~~Update script to not rerender entire screen on menu changes for faster refreshes and smoother usage.~~ - Done
* ~~Fix console resizing~~ - Done
* ~~Update script to do partial hotzone renderings (for build stack page) to better increase efficiency.~~ - Not required (pagination fixed)
* ~~Add ASCII switch to check if system supports latin or ASCII characters~~ - Done

Future TODO:
* Port Hass.io installer to new menu
* Start doing the installation specific menus, such as NodeRed module installer.
    * ~~NodeRed npm module selection~~ - Done
* ~~Add in port changing for services.~~ - Done
* ~~Add in options and auto preselection for containers that use specific hardware with new menu (such as `deconz`).~~ - Done
* Let `PiHole` and `nginx` services be auto configurable to auto route to containers (instead of `http://192.168.1.5:3455` for example, you could just use `http://iotstack/myservice`)
* Update all documentation
* Added refined rendering (Only updating diffs, not entire hotzone) for faster rendering speeds. - Partially done, not usable yet.
* ~~Scrolling pagination~~ - Done

### CODE REVIEW

**Comment by Willem-Dekker** [comment]
image
I can't see my cursor in the main menu. after updating the menu from master to this branch

**Comment by Willem-Dekker** [comment]
image
this keeps showing up even after update

**Comment by Willem-Dekker** [comment]
build stack does not seem to show cursor 
image

**Comment by Slyke** [comment]
Heh, I've not seen that before. It looks like the CLI doesn't have correct color mode set or something. Are you using putty or anything? Can you tell me more about the system you are using?

**Comment by Willem-Dekker** [comment]
I am testing it on a raspberry pi 3b running raspbian, using bitvise ssh client on windows 10 pro

**Comment by Willem-Dekker** [comment]
image
terminal settings i use i think they are default

**Comment by Slyke** [comment]
Yep, I can reproduce it using PuTTY:
image
image
image

Seems it only does it on some menus. Will investigate. Will probably fix when I fix the slow refresh rendering.

**Comment by Willem-Dekker** [comment]
image
when i press space to select add a container to the stack it crashes.

**Comment by Slyke** [comment]
Seems that was caused from some code I didn't push yesterday. I've pushed it now! I have also fixed resizing the console causing weirdness

**Comment by Slyke** [comment]
image
image
image
Pagination with fixed cursor highlighting on the buildstack menu.

**Comment by Slyke** [comment]
image
image
Nextcloud needs to be fixed (need to have nextcloud_db added to compose during prebuild hooks). Everything else works in so far as being able to run `docker-compose up -d`. Have to finish checking individual services now to ensure they all work.

**Pull request merged**
